AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'omnibus-ridgepole/**/*'
  TargetRubyVersion: 2.4
  NewCops: enable
Bundler/OrderedGems:
  Include:
    - 'Appraisals'
Layout/HeredocIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'spec/**/*'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/ClosingHeredocIndentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
